site_name: Bozio-Wasmer Simulations
site_url: https://IGF-PSD.github.io/bozio_wasmer_simulations/
repo_url: https://github.com/IGF-PSD/bozio_wasmer_simulations
site_dir: site
theme:
  name: material
  pygments_style: 'lovelace'
  logo: assets/logo-igf-transparent-blanc.png
  favicon: assets/logo-igf-transparent.png
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    #- navigation.expand
    - navigation.path
  palette:
   # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.sane_lists
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src, docs/snippets]
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          - https://python-markdown.github.io/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            show_root_heading: true 
            merge_init_into_class: false 
            docstring_style: google
            docstring_section_style: table
            heading_level: 1
            filters: ["!^_"]
            inherited_members: true
            parameter_headings: true
            preload_modules: [mkdocstrings]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: false
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML



nav:
  - Package description: index.md
  - Concepts:
    - Simulation: concepts/SIMULATIONS.md
    - Employment effects: concepts/EMPLOYMENT_EFFECTS.md
    - Measure of incentives to raise wages : concepts/MARGINAL_CAPTATION_RATE.md
  - API Documentation:
    - Datasets:
      - Loader: api/Loader.md
      - load_dads: api/load_dads.md
      - load_fare: api/load_fare.md
    - Description:
      - DescriptionBuilder: api/DescriptionBuilder.md
      - build_data_evol_emploi: api/build_data_evol_emploi.md
      - build_data_evol_ct: api/build_data_evol_ct.md
    - Simulation:
      - Empirical:
        - EmpiricalSimulator: api/EmpiricalSimulator.md
        - CoreSimulation: api/CoreSimulation.md
        - ReformSimulation: api/ReformSimulation.md
        - preprocess_dads_openfisca_ag: api/preprocess_dads_openfisca_ag.md
        - preprocess_simulated_variables: api/preprocess_simulated_variables.md
        - create_and_apply_structural_reform_ag: api/create_and_apply_structural_reform_ag.md
        - add_weights_eqtp_accos: api/add_weights_eqtp_accos.md
      - Theoretical: 
        - TheoreticalSimulator: api/TheoreticalSimulator.md
        - TheoreticalSimulation: api/TheoreticalSimulation.md
        - PPVReintegrationSimulator: api/PPVReintegrationSimulator.md
        - CaptationMarginaleSimulator: api/CaptationMarginaleSimulator.md